In [12]:
import numpy as np
a=np.array(([1,2,3,4],[2,34,55,5],[6,7,8,5]))
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 2 34 55  5]
 [ 6  7  8  5]]
(3, 4)


In [23]:
import numpy
import time
import sys

s=range(1000)

print("memory usage in procedural approach",sys.getsizeof(10)*len(s))

d=numpy.arange(1000)

print(d.size)
print(d.itemsize)
print("memory usage in numpy approach",d.itemsize*d.size)

memory usage in procedural approach 28000
1000
4
memory usage in numpy approach 4000


In [29]:
import numpy as np
a=np.array(([1,2,3,4],[3,4,5,6]))
print(a)
print(a.shape)
a=a.reshape(4,2)
print(a)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)
[[1 2]
 [3 4]
 [3 4]
 [5 6]]


In [30]:
a=a.repeat(4,0)
print(a)
print(a.shape)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]
 [5 6]]
(16, 2)


In [37]:
a=([9,8],[8,5],[4,5])
print(a)
print(a[1:2])

([9, 8], [8, 5], [4, 5])
([8, 5],)


In [40]:
import numpy as np
a=np.array(([1,2,3],[2,3,4]))
print(a)
print(a.shape)
print("Max value of array a is",a.max())
print("Min value of array a is",a.min())
print("Sum of array a is",a.sum())

[[1 2 3]
 [2 3 4]]
(2, 3)
Max value of array a is 4
Min value of array a is 1
Sum of array a is 15


In [41]:
#col and row addition
print(a.sum(axis=0))   #for col addition
print(a.sum(axis=1))   #for row addition


[3 5 7]
[6 9]


In [47]:
import numpy as np
a=np.array(([1,2,3,4],[3,4,5,6],[5,7,8,9]))
b=np.array(([3,2,4,1],[5,7,9,8],[7,5,6,4]))
print(a)
print(b)



[[1 2 3 4]
 [3 4 5 6]
 [5 7 8 9]]
[[3 2 4 1]
 [5 7 9 8]
 [7 5 6 4]]


In [50]:
print(np.sqrt(a))
print(np.sqrt(a+b))

[[1.         1.41421356 1.73205081 2.        ]
 [1.73205081 2.         2.23606798 2.44948974]
 [2.23606798 2.64575131 2.82842712 3.        ]]
[[2.         2.         2.64575131 2.23606798]
 [2.82842712 3.31662479 3.74165739 3.74165739]
 [3.46410162 3.46410162 3.74165739 3.60555128]]


In [52]:
print(np.std(a))

2.3139072294858036


In [54]:
print(np.shape(a))

(3, 4)


In [56]:
print(a/b)

[[0.33333333 1.         0.75       4.        ]
 [0.6        0.57142857 0.55555556 0.75      ]
 [0.71428571 1.4        1.33333333 2.25      ]]


In [61]:
print(a.max())
print(a.min())


9
1


In [64]:
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [66]:
help(numpy)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [73]:
# Stacking
print(np.shape(a))
print(np.shape(b))

print(np.hstack((a,b)))
print(np.hstack((a,b)).shape)

(3, 4)
(3, 4)
[[1 2 3 4 3 2 4 1]
 [3 4 5 6 5 7 9 8]
 [5 7 8 9 7 5 6 4]]
(3, 8)


In [75]:
# Stacking
print(np.shape(a))
print(np.shape(b))

print(np.vstack((a,b)))
print(np.vstack((a,b)).shape)

(3, 4)
(3, 4)
[[1 2 3 4]
 [3 4 5 6]
 [5 7 8 9]
 [3 2 4 1]
 [5 7 9 8]
 [7 5 6 4]]
(6, 4)


In [78]:
import numpy as np
a=np.arange(10)
print(a)
s=slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [80]:
import numpy as np
a=np.arange(10)
print(a)
b=a[2:9:2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [86]:
# version of numpy on my system
numpy.__version__


'1.17.0'

In [92]:
# convrt list into array
a=[12.23,13.32,100,36.32]
print(a)
b=np.array(a)
print(b)

[12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


In [95]:
# write a matrix
a=np.array(([2,3,4],[5,6,7],[8,9,10]))
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [103]:
# write zero vector with 10 zeros and then replace sixth zero to 11
a=np.zeros(10)
print(a)
a[6]=11
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
